In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/My_project/dataset.csv')


In [4]:
df.columns

Index(['prompttext_clean', 'text_clean', 'text_cnt_stopwords', 'text_cntpunct',
       'text_wordcnt', 'text_length', 'text_syllablecnt', 'text_ARI',
       'text_GFI', 'text_cntverb', 'text_cntadjctv', 'text_cntadvrb',
       'text_cntnoun', 'text_cntpronoun', 'text_cntspecificpos', 'text_bigram',
       'text_trigram', 'text_misspellcnt', 'text_unique',
       'cos_similarity_text_prompt', 'content', 'wording'],
      dtype='object')

In [5]:
df.head(2)

prompttext_clean  \
0  chapter sequel already say must proceed consid...   
1  chapter sequel already say must proceed consid...   

                                          text_clean  text_cnt_stopwords  \
0  element ideal tragedy arrange complex plan ano...                  31   
1  three element ideal tragedy character not bad ...                  12   

   text_cntpunct  text_wordcnt  text_length  text_syllablecnt  text_ARI  \
0              3            55          285                94     25.85   
1              6            26          143                44     12.95   

   text_GFI  text_cntverb  ...  text_cntnoun  text_cntpronoun  \
0     24.18             3  ...            11                3   
1     15.02             3  ...             6                2   

   text_cntspecificpos  text_bigram  text_trigram  text_misspellcnt  \
0                    5           54            53                 0   
1                    2           25            24                 1   

   text_unique  cos_similarity_text_prompt   content   wording  
0           33                    0.167416 -0.210614 -0.471415  
1           25                    0.172985 -0.970237 -0.417058  

[2 rows x 22 columns]

In [6]:
X = df.drop(['content','wording'],axis=1).values
Y = df[['content','wording']]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y, random_state=100, test_size=0.2)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [9]:
x_traintext = x_train[:,:2]

In [10]:
x_traintxt_list = x_traintext.tolist()  # Convert to list (if needed)
x_traintxt_list = [" ".join(map(str, doc)) for doc in x_traintxt_list]  # Join words into strings

# Rest of your code (vectorization, model training, etc.)

x_traintxt_vtrsd = vectorizer.fit_transform(x_traintxt_list)

In [11]:
type(x_traintxt_vtrsd)

scipy.sparse._csr.csr_matrix

In [12]:
len(vectorizer.get_feature_names_out())

9106

In [13]:
x_train.shape

(5572, 20)

In [14]:
x_trainnum = x_train[:,2:]


In [15]:
dense_array = x_traintxt_vtrsd.toarray()

In [16]:
dense_array.shape

(5572, 9106)

In [17]:
merged_array = np.hstack((dense_array, x_trainnum))

In [18]:
merged_array

array([[0.0, 0.0, 0.0, ..., 2, 77, 0.4839867708409886],
       [0.0, 0.0, 0.0, ..., 0, 26, 0.4387080703839858],
       [0.0, 0.0, 0.0, ..., 3, 31, 0.1428077141977683],
       ...,
       [0.0, 0.0, 0.0, ..., 3, 64, 0.4722183975941029],
       [0.0, 0.0, 0.0, ..., 2, 53, 0.287440703604517],
       [0.0, 0.0, 0.0, ..., 1, 83, 0.5461951065400601]], dtype=object)

In [19]:
x_testtext = x_test[:,:2]
x_testnum = x_test[:,2:]

In [20]:
x_testxt_list = x_testtext.tolist()  # Convert to list (if needed)
x_testxt_list = [" ".join(map(str, doc)) for doc in x_testxt_list]  # Join words into strings

# Rest of your code (vectorization, model training, etc.)

x_testtxt_vtrsd = vectorizer.transform(x_testxt_list)

In [21]:
densetest_array = x_testtxt_vtrsd.toarray()


In [22]:
mergedtest_array = np.hstack((densetest_array, x_testnum))


In [24]:
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [25]:
model = MultiOutputRegressor(GradientBoostingRegressor(random_state=0)).fit(merged_array,y_train)
predi = model.predict(mergedtest_array)
r2_score(y_test,predi)

0.6848979964507862

In [27]:
print(mean_absolute_error(y_test,predi))
print(mean_squared_error(y_test,predi))

0.41721487557501763
0.29665788887334277


In [30]:
from sklearn import metrics

metrics.get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',

In [34]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeRegressor


# Define a regressor (e.g., RandomForestRegressor)
base_regressor = DecisionTreeRegressor()

# Wrap the regressor in MultiOutputRegressor
multioutput_regressor = MultiOutputRegressor(base_regressor)

# Use cross_val_score for evaluation
scores = cross_val_score(multioutput_regressor, merged_array,y_train, cv=5, scoring='r2', n_jobs=-1)

# Display the mean cross-validated score (negative mean squared error)
print(scores)
mean_score = scores.mean()
print("Mean Cross-Validated Score ( R2 score):", mean_score)



[0.32909689 0.40311601 0.37554648 0.36689167 0.38058655]
Mean Cross-Validated Score ( R2 score): 0.37104751898762195


In [36]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

# Define a regressor (e.g., RandomForestRegressor)
base_regressor = LinearRegression()

# Wrap the regressor in MultiOutputRegressor
multioutput_regressor = MultiOutputRegressor(base_regressor)

# Use cross_val_score for evaluation
scores = cross_val_score(multioutput_regressor, merged_array,y_train, cv=5, scoring='r2', n_jobs=-1)

# Display the mean cross-validated score (negative mean squared error)
mean_score = scores.mean()
print(scores)
print("Mean Cross-Validated Score (R2 score):", mean_score)



[-1.07546116e+14 -1.51688775e+13 -2.39989320e+13 -1.36712388e+13
 -2.50601973e+14]
Mean Cross-Validated Score (R2 score): -82197427566821.7


In [37]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor


# Define a regressor (e.g., RandomForestRegressor)
base_regressor = RandomForestRegressor()

# Wrap the regressor in MultiOutputRegressor
multioutput_regressor = MultiOutputRegressor(base_regressor)

# Use cross_val_score for evaluation
scores = cross_val_score(multioutput_regressor, merged_array,y_train, cv=5, scoring='r2', n_jobs=-1)

# Display the mean cross-validated score (negative mean squared error)
mean_score = scores.mean()
print(scores)
print("Mean Cross-Validated Score (R2 score):", mean_score)



[0.6862061  0.66514509 0.66297606 0.68072218 0.67959122]
Mean Cross-Validated Score (R2 score): 0.6749281307273517


In [38]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVR


# Define a regressor
base_regressor = SVR()

# Wrap the regressor in MultiOutputRegressor
multioutput_regressor = MultiOutputRegressor(base_regressor)

# Use cross_val_score for evaluation
scores = cross_val_score(multioutput_regressor, merged_array,y_train, cv=5, scoring='r2', n_jobs=-1)

mean_score = scores.mean()
print(scores)
print("Mean Cross-Validated Score (R2 score):", mean_score)



[0.55015206 0.5439918  0.50693476 0.54704297 0.55585573]
Mean Cross-Validated Score (R2 score): 0.5407954619497511
